name: Create Custom Release Assets
permissions:
  contents: write
  packages: read

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create custom zip files
        id: create_zips
        run: |
          # Extract the tag name from the GitHub ref
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Find the matching config file
          CONFIG_FILE="sparse-checkout-configs/${TAG_NAME}.txt"
          
          if [ -f "$CONFIG_FILE" ]; then
            echo "Creating zip for $TAG_NAME"
            git config core.sparseCheckout true
            cp "$CONFIG_FILE" .git/info/sparse-checkout
            git read-tree -mu HEAD
            zip -r "${TAG_NAME}.zip" . -x ".git/*" "config/*"
            echo "Created ${TAG_NAME}.zip"
            echo "::set-output name=zip_file::${TAG_NAME}.zip"
          else
            echo "No matching config file found for tag $TAG_NAME"
            exit 1
          fi

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.create_zips.outputs.zip_file }}
          asset_name: ${{ steps.create_zips.outputs.zip_file }}
          asset_content_type: application/zip